services:
  workflow-caller:
    image: workflow-caller
    container_name: workflow-caller-release
    environment:
      PORT: ${INTERNAL_PORT}
      NODE_ENV: production
      GIT_HUB_APP_ID_PATH: /app/secrets/github_appid
      GIT_HUB_APP_PRIVATE_KEY_PATH: /app/secrets/github_app_private_key
      OIDC_AUDIENCE_IDENTIFIER: ${WORKFLOW_CALL_OIDC_AUDIENCE_IDENTIFIER}
      AUTHORIZATION_CONFIG_PATH: ${WORKFLOW_CALL_AUTHORIZATION_CONFIG_PATH_INTERNAL}
    volumes:
      - ${WORKFLOW_CALL_AUTHORIZATION_CONFIG_PATH_EXTERNAL}:${WORKFLOW_CALL_AUTHORIZATION_CONFIG_PATH_INTERNAL}:ro
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    secrets:
      - source: github_appid
        target: /app/secrets/github_appid
      - source: github_app_private_key
        target: /app/secrets/github_app_private_key
  workflow-caller-debug:
    image: workflow-caller-debug
    container_name: workflow-caller-debug
    environment:
      PORT: ${INTERNAL_PORT}
      NODE_ENV: development
      GIT_HUB_APP_ID_PATH: /app/secrets/github_appid
      GIT_HUB_APP_PRIVATE_KEY_PATH: /app/secrets/github_app_private_key
      OIDC_AUDIENCE_IDENTIFIER: ${WORKFLOW_CALL_OIDC_AUDIENCE_IDENTIFIER}
      AUTHORIZATION_CONFIG_PATH: ${WORKFLOW_CALL_AUTHORIZATION_CONFIG_PATH_INTERNAL}
    volumes:
      - ${WORKFLOW_CALL_AUTHORIZATION_CONFIG_PATH_EXTERNAL}:${WORKFLOW_CALL_AUTHORIZATION_CONFIG_PATH_INTERNAL}:ro
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
      - "${EXTERNAL_DEBUG_PORT}:9229"
    secrets:
      - source: github_appid
        target: /app/secrets/github_appid
      - source: github_app_private_key
        target: /app/secrets/github_app_private_key

secrets:
  github_appid:
    file: ${WORKFLOW_CALL_GITHUB_APP_ID_PATH}
  github_app_private_key:
    file: ${WORKFLOW_CALL_GITHUB_APP_PRIVATE_KEY_PATH}