services:
  workflow-caller:
    image: workflow-caller-debug
    environment:
      PORT: ${INTERNAL_PORT}
      NODE_ENV: development
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
      - "${EXTERNAL_DEBUG_PORT}:9229"
    secrets:
      - github_private_key

secrets:
  github_private_key:
    external: true