services:
  workflow-caller:
    image: workflow-caller
    container_name: release
    environment:
      PORT: ${INTERNAL_PORT}
      NODE_ENV: production
      GIT_HUB_APP_ID: ${WORKFLOW_CALL_GITHUB_APP_ID}
      OICD_AUDIENCE_IDENTIFIER: ${WORKFLOW_CALL_OICD_AUDIENCE_IDENTIFIER}
      GIT_HUB_APP_PRIVATE_KEY_SECRET_NAME: github_app_private_key
      AUTHORIZATION_CONFIG_PATH: ${WORKFLOW_CALL_AUTHORIZATION_CONFIG_PATH_INTERNAL}
    volumes:
      - ${WORKFLOW_CALL_AUTHORIZATION_CONFIG_PATH_EXTERNAL}:${WORKFLOW_CALL_AUTHORIZATION_CONFIG_PATH_INTERNAL}:ro
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    secrets:
      - github_app_private_key
  workflow-caller-debug:
    image: workflow-caller-debug
    container_name: debug
    environment:
      PORT: ${INTERNAL_PORT}
      NODE_ENV: development
      GIT_HUB_APP_ID: ${WORKFLOW_CALL_GITHUB_APP_ID}
      OICD_AUDIENCE_IDENTIFIER: ${WORKFLOW_CALL_OICD_AUDIENCE_IDENTIFIER}
      GIT_HUB_APP_PRIVATE_KEY_SECRET_NAME: github_app_private_key
      AUTHORIZATION_CONFIG_PATH: ${WORKFLOW_CALL_AUTHORIZATION_CONFIG_PATH_INTERNAL}
    volumes:
      - ${WORKFLOW_CALL_AUTHORIZATION_CONFIG_PATH_EXTERNAL}:${WORKFLOW_CALL_AUTHORIZATION_CONFIG_PATH_INTERNAL}:ro
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
      - "${EXTERNAL_DEBUG_PORT}:9229"
    secrets:
      - github_app_private_key

secrets:
  github_app_private_key:
    file: ${WORKFLOW_CALL_GITHUB_APP_PRIVATE_KEY_PATH}