name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. 1.2.3)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker buildx create --name mybuilder --driver docker-container --use &&
          # docker buildx build --output=type=docker,dest=workflow-caller_arm64.tar \
          docker buildx build --output=type=docker \
            --provenance=false \
            --tag workflow-caller:arm64 \
            --platform=linux/arm64 \
            -f Dockerfile .

      - name: Set Docker Login info
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Docker image to GHCR
        env:
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          docker tag workflow-caller:arm64 ghcr.io/"$REPO_OWNER"/workflow-caller:arm64
          docker push ghcr.io/"$REPO_OWNER"/workflow-caller:arm64

      # - name: Compress Docker image
      #   run: gzip workflow-caller_arm64.tar

      - name: Set git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create Git tags
        run: |
          git tag -a v${{ github.event.inputs.version }} -m "Release v${{ github.event.inputs.version }}"
          git push origin v${{ github.event.inputs.version }}

          git tag -f v0 -m "Release v${{ github.event.inputs.version }}"
          git push --force origin v0

          git fetch origin --tags
          git tag -f latest -m "Release v${{ github.event.inputs.version }}"
          git push --force origin latest

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          generate_release_notes: true
          # files: workflow-caller_arm64.tar.gz